export enum ReconciliationStatus {
  MATCHED = 'MATCHED',
  UNMATCHED = 'UNMATCHED',
  RESOLVED = 'RESOLVED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum ExceptionStatus {
  OPEN = 'OPEN',
  PROPOSED = 'PROPOSED',
  RESOLVED = 'RESOLVED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  UNRESOLVED = 'UNRESOLVED',
}

export enum ExceptionType {
  SETTLEMENT_MISMATCH = 'SETTLEMENT_MISMATCH',
  MISSING_BANK_RECORD = 'MISSING_BANK_RECORD',
  AMBIGUOUS_MATCH = 'AMBIGUOUS_MATCH',
  TAX_MISMATCH = 'TAX_MISMATCH',
}

export enum AgentType {
  CONTROLLER = 'CONTROLLER',
  RECONCILIATION = 'RECONCILIATION',
  EXCEPTION_INVESTIGATOR = 'EXCEPTION_INVESTIGATOR',
  SETTLEMENT = 'SETTLEMENT',
  TAX = 'TAX',
  FORECAST = 'FORECAST',
  EXPENSE_CATEGORIZER = 'EXPENSE_CATEGORIZER',
}

export enum RecordSource {
  PAYMENT = 'PAYMENT',
  BANK = 'BANK',
  INVOICE = 'INVOICE',
  TAX = 'TAX',
}

export enum CashDirection {
  INFLOW = 'INFLOW',
  OUTFLOW = 'OUTFLOW',
}

export enum CashMovementStatus {
  POSTED = 'POSTED',
  SCHEDULED = 'SCHEDULED',
  CANCELLED = 'CANCELLED',
}

export enum CashMovementCategory {
  COLLECTION = 'COLLECTION',
  GATEWAY_FEE = 'GATEWAY_FEE',
  GST = 'GST',
  REFUND = 'REFUND',
  VENDOR_PAYMENT = 'VENDOR_PAYMENT',
  PAYROLL = 'PAYROLL',
  RENT = 'RENT',
  TAX_PAYMENT = 'TAX_PAYMENT',
  TRAVEL = 'TRAVEL',
  MEALS = 'MEALS',
  LODGING = 'LODGING',
  LOCAL_TRANSPORT = 'LOCAL_TRANSPORT',
  SOFTWARE = 'SOFTWARE',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  MARKETING = 'MARKETING',
  PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES',
  UTILITIES = 'UTILITIES',
  OTHER = 'OTHER',
}

export enum WorkspaceRole {
  EMPLOYEE = 'EMPLOYEE',
  FINANCE_OPERATOR = 'FINANCE_OPERATOR',
  FINANCE_CONTROLLER = 'FINANCE_CONTROLLER',
  ENTERPRISE_ADMIN = 'ENTERPRISE_ADMIN',
  AUDITOR = 'AUDITOR',
}

export enum WorkspacePermission {
  VIEW_OWN_FINANCE = 'VIEW_OWN_FINANCE',
  VIEW_ORGANIZATION_FINANCE = 'VIEW_ORGANIZATION_FINANCE',
  SUBMIT_EXPENSE = 'SUBMIT_EXPENSE',
  REVIEW_EXPENSE = 'REVIEW_EXPENSE',
  MANAGE_BUDGET = 'MANAGE_BUDGET',
  MANAGE_SPEND_LIMIT = 'MANAGE_SPEND_LIMIT',
  MANAGE_ORGANIZATION = 'MANAGE_ORGANIZATION',
  MANAGE_AGENT_SKILL = 'MANAGE_AGENT_SKILL',
  VIEW_AGENT_AUDIT = 'VIEW_AGENT_AUDIT',
  APPROVE_FINANCE_ACTION = 'APPROVE_FINANCE_ACTION',
  MANAGE_INTEGRATION = 'MANAGE_INTEGRATION',
}

export enum OrganizationNodeType {
  COMPANY = 'COMPANY',
  LEGAL_ENTITY = 'LEGAL_ENTITY',
  OFFICE = 'OFFICE',
  DEPARTMENT = 'DEPARTMENT',
  TEAM = 'TEAM',
  COST_CENTER = 'COST_CENTER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum BudgetStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
}

export enum SpendLimitStatus {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
}

export enum ExpenseCategorySource {
  USER = 'USER',
  AI = 'AI',
  RULE = 'RULE',
  IMPORT = 'IMPORT',
}

export enum ExpenseCategoryStatus {
  SUGGESTED = 'SUGGESTED',
  CONFIRMED = 'CONFIRMED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum InvoiceDirection {
  RECEIVABLE = 'RECEIVABLE',
  PAYABLE = 'PAYABLE',
}

export enum ImportRecordType {
  INVOICE = 'INVOICE',
  EXPENSE = 'EXPENSE',
}

export enum ImportBatchStatus {
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_ERRORS = 'COMPLETED_WITH_ERRORS',
  FAILED = 'FAILED',
}

export enum ExpenseClaimStatus {
  DRAFT = 'DRAFT',
  RECEIPT_REQUIRED = 'RECEIPT_REQUIRED',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REIMBURSED = 'REIMBURSED',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  PROCESSING = 'PROCESSING',
  EXTRACTED = 'EXTRACTED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  REJECTED = 'REJECTED',
}

export enum ReceiptRequestStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  RECEIVED = 'RECEIVED',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum AgentSkillStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  SLACK = 'SLACK',
  EMAIL = 'EMAIL',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  READ = 'READ',
}

export enum IntegrationType {
  PAYMENT = 'PAYMENT',
  BANKING = 'BANKING',
  ERP = 'ERP',
  MESSAGING = 'MESSAGING',
  DOCUMENT_STORAGE = 'DOCUMENT_STORAGE',
}

export enum IntegrationProvider {
  RAZORPAY = 'RAZORPAY',
  MOCK_PAYMENT = 'MOCK_PAYMENT',
  MOCK_BANKING = 'MOCK_BANKING',
  GENERIC_ERP = 'GENERIC_ERP',
  SLACK = 'SLACK',
  LOCAL_DOCUMENTS = 'LOCAL_DOCUMENTS',
}

export enum IntegrationStatus {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTED = 'CONNECTED',
  ERROR = 'ERROR',
}

export enum AutomationJobType {
  RECEIPT_REMINDER = 'RECEIPT_REMINDER',
  INTEGRATION_SYNC = 'INTEGRATION_SYNC',
  DOCUMENT_PROCESSING = 'DOCUMENT_PROCESSING',
  RECONCILIATION = 'RECONCILIATION',
  TAX_MATCH = 'TAX_MATCH',
  FORECAST_REFRESH = 'FORECAST_REFRESH',
}

export enum AutomationJobStatus {
  IDLE = 'IDLE',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum TaxMatchStatus {
  MATCHED = 'MATCHED',
  AMBIGUOUS = 'AMBIGUOUS',
  UNMATCHED = 'UNMATCHED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}
