export enum ReconciliationStatus {
  MATCHED = 'MATCHED',
  UNMATCHED = 'UNMATCHED',
  RESOLVED = 'RESOLVED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum ExceptionStatus {
  OPEN = 'OPEN',
  PROPOSED = 'PROPOSED',
  RESOLVED = 'RESOLVED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  UNRESOLVED = 'UNRESOLVED',
}

export enum ExceptionType {
  SETTLEMENT_MISMATCH = 'SETTLEMENT_MISMATCH',
  MISSING_BANK_RECORD = 'MISSING_BANK_RECORD',
  AMBIGUOUS_MATCH = 'AMBIGUOUS_MATCH',
  TAX_MISMATCH = 'TAX_MISMATCH',
}

export enum AgentType {
  CONTROLLER = 'CONTROLLER',
  RECONCILIATION = 'RECONCILIATION',
  EXCEPTION_INVESTIGATOR = 'EXCEPTION_INVESTIGATOR',
  SETTLEMENT = 'SETTLEMENT',
  TAX = 'TAX',
  FORECAST = 'FORECAST',
}

export enum RecordSource {
  PAYMENT = 'PAYMENT',
  BANK = 'BANK',
  INVOICE = 'INVOICE',
  TAX = 'TAX',
}
