export enum ReconciliationStatus {
  MATCHED = 'MATCHED',
  UNMATCHED = 'UNMATCHED',
  RESOLVED = 'RESOLVED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum ExceptionStatus {
  OPEN = 'OPEN',
  PROPOSED = 'PROPOSED',
  RESOLVED = 'RESOLVED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  UNRESOLVED = 'UNRESOLVED',
}

export enum ExceptionType {
  SETTLEMENT_MISMATCH = 'SETTLEMENT_MISMATCH',
  MISSING_BANK_RECORD = 'MISSING_BANK_RECORD',
  AMBIGUOUS_MATCH = 'AMBIGUOUS_MATCH',
  TAX_MISMATCH = 'TAX_MISMATCH',
}

export enum AgentType {
  CONTROLLER = 'CONTROLLER',
  RECONCILIATION = 'RECONCILIATION',
  EXCEPTION_INVESTIGATOR = 'EXCEPTION_INVESTIGATOR',
  SETTLEMENT = 'SETTLEMENT',
  TAX = 'TAX',
  FORECAST = 'FORECAST',
}

export enum RecordSource {
  PAYMENT = 'PAYMENT',
  BANK = 'BANK',
  INVOICE = 'INVOICE',
  TAX = 'TAX',
}

export enum CashDirection {
  INFLOW = 'INFLOW',
  OUTFLOW = 'OUTFLOW',
}

export enum CashMovementStatus {
  POSTED = 'POSTED',
  SCHEDULED = 'SCHEDULED',
  CANCELLED = 'CANCELLED',
}

export enum CashMovementCategory {
  COLLECTION = 'COLLECTION',
  GATEWAY_FEE = 'GATEWAY_FEE',
  GST = 'GST',
  REFUND = 'REFUND',
  VENDOR_PAYMENT = 'VENDOR_PAYMENT',
  PAYROLL = 'PAYROLL',
  RENT = 'RENT',
  TAX_PAYMENT = 'TAX_PAYMENT',
  OTHER = 'OTHER',
}
